name: Release CI

permissions:
  contents: read
  packages: read
  actions: read

on:
  release:
    types: [published]
  # allow manually triggering the build
  workflow_dispatch:

jobs:
  build_python_packages:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          # use the minimum py ver we support to generate the wheel
          python-version-file: ".python-version"

      - name: Build python package
        run: |
          uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-python-packages
          path: dist/*

  build_and_release_ota_image_tools:
    runs-on: ubuntu-latest
    container:
      # glibc compatible with ubuntu:20.04 and newer
      image: debian:bullseye

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            git curl ca-certificates binutils

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version-file: ".python-version_ota_image_tools"

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          version: "0.10.11"

      - name: Build binary with PyInstaller
        run: |
          uv run --locked pyinstaller \
            --onefile -s \
            --name ota-image-tools \
            --clean \
            src/ota_image_tools/__main__.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-ota-image-tools
          path: dist/*

  post_build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    needs: [build_python_packages, build_and_release_ota_image_tools]
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download python packages artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts-python-packages
          path: dist

      - name: Download ota-image-tools binary
        uses: actions/download-artifact@v4
        with:
          name: artifacts-ota-image-tools
          path: dist

      - name: Calculate artifacts' checksum
        uses: ./.github/actions/calculate_checksum
        with:
          file_patterns: '*'
          directory: 'dist'

      - name: Publish release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*